name: SkyBlock Alpha
version: 0.1.0.4
api: [1.13.0]
main: SkyBlock\Main
commands:
  is:
    Uso: /is <help> <pagina>
    description: Lista de comandos de SkyBlock
    permission: is.command.help
permissions:
  is:
    default: false
    description: Permite al Jugador usar las caracteristicas de SkyBlock
    children:
      is.command:
        default: op
        description: Permite al Jugador usar todos los comandos de SkyBlock
        children:
          is.command.help:
            default: true
            description: Permite l Jugador usar el comando de ayuda
            is.command.create:
            default: true
            description: Permite al Jugador usar el comando crear
          is.command.find:
            default: op
            description: Permite al Jugador usar el comando Home
          is.command.delete:
            default: true
            description: Permite al Jugador elminiar su isla
          is.command.sethome:
            default: true
            description: Permite al Jugador poner el lugar Home
          is.command.home:
            default: true
            description: Permite al jugador a teletransportarse a su isla
        
