name: SkyBlockXT
version: 0.0.1
api: [2.0.0, 1.14.0, 1.13.1, 1.13.0, 1.12.0]
main: SkyBlockXT\Main
desc: An Awesome SkyBlock Plugin! With extended Support and Features!
author: XenoNova Team Project (XNT), TKRT Creations (C)
load: STARTUP
website: http://thekillertacos.tk/
commands:
  is:
    usage: /is <help> <page>
    description: Tells the player a list of SkyBlockXT commands
    permission: is.command.help
  skyworld:
    usage: /skyworld <help> <page> 
    description: SkyWorld Generator Commands
    permission: skyWorld.cmd.help
permissions:
  skyworld:
    default: op
    description: SkyWorld Permissions For OPs only! 
    children:
      skyworld.cmd:
        default: op
        description: Main SkyWorld Permission
        children:
          skyworld.cmd.help:
            default: op
            description: SkyWorld Permission for Help
          skyworld.cmd.genworld:
            default: op
            description: SkyWorld Permission for World Generation
          skyworld.cmd.delworld:
            default: op
            description: SkyWorld Permission for World Deletion
          skyworld.cmd.config:
            default: op
            description: SkyWorld Permission for Configurations commands
            children:
              skyworld.cmd.config.isperworld:
                default: op
                description: Configuration Permission for changing Island generated per world
  is:
    default: false
    description: Allows the player to use all of the SkyBlockXT features
    children:
      is.command:
        default: op
        description: Allows the player to use all of the SkyBlockXT commands
        children:
          is.command.help:
            default: true
            description: Allows the player to use the help command
          is.command.create:
            default: true
            description: Allows the player to use the create command
          is.command.delete:
            default: true
            description: Allows the player to delete their island
          is.command.sethome:
            default: true
            description: Allows the player to set their island coords
          is.command.home:
            default: true
            description: Allows the player to teleport to their island
        
